// This catalog is intentionally additive. Certifications already present inside
// roadmaps.js and languages.js are not repeated here.
export const certificationCategories = {
  ai: 'Artificial Intelligence',
  cloud: 'Cloud Computing',
  data: 'Data and Analytics',
  engineering: 'Software Engineering',
  security: 'Cybersecurity',
  support: 'IT Support',
};

export const certifications = [
  {
    id: 'microsoft-azure-ai-fundamentals',
    name: 'Microsoft Certified: Azure AI Fundamentals',
    provider: 'Microsoft',
    description: 'Validate foundational knowledge of AI workloads, machine learning, generative AI, and Azure AI services.',
    category: 'ai',
    difficulty: 'Beginner',
    duration: '4–6 weeks',
    costType: 'Paid',
    skills: ['AI workloads', 'Machine learning concepts', 'Generative AI', 'Azure AI services'],
    officialUrl: 'https://learn.microsoft.com/en-us/credentials/certifications/azure-ai-fundamentals/',
    providerLogo: '',
    recommendedCareerPaths: ['ai-engineer', 'ml-engineer', 'data-science'],
  },
  {
    id: 'microsoft-security-compliance-identity-fundamentals',
    name: 'Microsoft Security, Compliance, and Identity Fundamentals',
    provider: 'Microsoft',
    description: 'Build a grounding in Zero Trust, Microsoft Entra, security solutions, compliance, and identity concepts.',
    category: 'security',
    difficulty: 'Beginner',
    duration: '4–6 weeks',
    costType: 'Paid',
    skills: ['Zero Trust', 'Identity concepts', 'Microsoft Entra', 'Compliance fundamentals'],
    officialUrl:
      'https://learn.microsoft.com/en-us/credentials/certifications/security-compliance-and-identity-fundamentals/',
    providerLogo: '',
    recommendedCareerPaths: ['cybersecurity', 'it-support-specialist', 'cloud-engineer'],
  },
  {
    id: 'microsoft-power-platform-fundamentals',
    name: 'Microsoft Certified: Power Platform Fundamentals',
    provider: 'Microsoft',
    description: 'Learn how low-code tools, Dataverse, Power Apps, and Power Automate support business solutions.',
    category: 'engineering',
    difficulty: 'Beginner',
    duration: '4–6 weeks',
    costType: 'Paid',
    skills: ['Power Apps', 'Power Automate', 'Dataverse', 'Low-code solution design'],
    officialUrl: 'https://learn.microsoft.com/en-us/credentials/certifications/power-platform-fundamentals/',
    providerLogo: '',
    recommendedCareerPaths: ['fullstack-dev', 'data-analyst', 'it-support-specialist'],
  },
  {
    id: 'aws-certified-ai-practitioner',
    name: 'AWS Certified AI Practitioner',
    provider: 'AWS',
    description: 'Demonstrate foundational understanding of AI, machine learning, generative AI, and responsible AI on AWS.',
    category: 'ai',
    difficulty: 'Beginner',
    duration: '6–8 weeks',
    costType: 'Paid',
    skills: ['AI and ML concepts', 'Generative AI', 'Responsible AI', 'AWS AI services'],
    officialUrl: 'https://aws.amazon.com/certification/certified-ai-practitioner/',
    providerLogo: '',
    recommendedCareerPaths: ['ai-engineer', 'cloud-engineer', 'data-science'],
  },
  {
    id: 'google-cybersecurity-professional',
    name: 'Google Cybersecurity Professional Certificate',
    provider: 'Google',
    description: 'Prepare for entry-level security work through hands-on Linux, SQL, Python, SIEM, and incident-response practice.',
    category: 'security',
    difficulty: 'Beginner',
    duration: 'Up to 6 months',
    costType: 'Financial Aid Available',
    skills: ['Linux', 'SQL', 'Python', 'SIEM', 'Incident response'],
    officialUrl: 'https://www.coursera.org/professional-certificates/google-cybersecurity',
    providerLogo: '',
    recommendedCareerPaths: ['cybersecurity', 'network-technician', 'it-support-specialist'],
  },
  {
    id: 'google-advanced-data-analytics',
    name: 'Google Advanced Data Analytics Professional Certificate',
    provider: 'Google',
    description: 'Advance from analysis into statistics, regression, machine learning, and stakeholder-ready data storytelling.',
    category: 'data',
    difficulty: 'Intermediate',
    duration: 'Up to 6 months',
    costType: 'Financial Aid Available',
    skills: ['Statistics', 'Regression analysis', 'Python', 'Machine learning', 'Data storytelling'],
    officialUrl: 'https://www.coursera.org/professional-certificates/google-advanced-data-analytics',
    providerLogo: '',
    recommendedCareerPaths: ['data-analyst', 'data-science', 'ml-engineer'],
  },
  {
    id: 'ibm-cybersecurity-analyst',
    name: 'IBM Cybersecurity Analyst Professional Certificate',
    provider: 'IBM',
    description: 'Develop practical security operations, threat intelligence, incident response, and job-search skills.',
    category: 'security',
    difficulty: 'Beginner',
    duration: '4–8 months',
    costType: 'Financial Aid Available',
    skills: ['Security operations', 'Threat intelligence', 'Incident response', 'Network security'],
    officialUrl: 'https://www.coursera.org/professional-certificates/ibm-cybersecurity-analyst',
    providerLogo: '',
    recommendedCareerPaths: ['cybersecurity', 'network-engineer', 'it-support-specialist'],
  },
  {
    id: 'ibm-devops-software-engineering',
    name: 'IBM DevOps and Software Engineering Professional Certificate',
    provider: 'IBM',
    description: 'Build job-ready skills across Python, Linux, containers, Kubernetes, microservices, testing, and CI/CD.',
    category: 'engineering',
    difficulty: 'Beginner',
    duration: '6 months',
    costType: 'Financial Aid Available',
    skills: ['Python', 'Linux', 'Docker', 'Kubernetes', 'CI/CD', 'Microservices'],
    officialUrl: 'https://www.coursera.org/professional-certificates/devops-and-software-engineering',
    providerLogo: '',
    recommendedCareerPaths: ['devops', 'backend-dev', 'cloud-engineer'],
  },
  {
    id: 'github-foundations',
    name: 'GitHub Foundations Certification',
    provider: 'GitHub',
    description: 'Validate foundational Git, repository, collaboration, and GitHub product knowledge.',
    category: 'engineering',
    difficulty: 'Beginner',
    duration: '3–5 weeks',
    costType: 'Paid',
    skills: ['Git basics', 'Repositories', 'Collaboration', 'Branches and pull requests'],
    officialUrl:
      'https://docs.github.com/en/get-started/showcase-your-expertise-with-github-certifications/about-github-certifications',
    providerLogo: '',
    recommendedCareerPaths: ['frontend-dev', 'backend-dev', 'fullstack-dev', 'devops'],
  },
  {
    id: 'linux-foundation-certified-it-associate',
    name: 'Linux Foundation Certified IT Associate',
    provider: 'Linux Foundation',
    description: 'Confirm broad entry-level knowledge of Linux, cloud, networking, security, DevOps, and IT operations.',
    category: 'support',
    difficulty: 'Beginner',
    duration: '3–6 months',
    costType: 'Paid',
    skills: ['Linux', 'System administration', 'Networking', 'Cloud fundamentals', 'DevOps basics'],
    officialUrl: 'https://training.linuxfoundation.org/certification/certified-it-associate/',
    providerLogo: '',
    recommendedCareerPaths: ['it-support-specialist', 'network-technician', 'devops', 'cloud-engineer'],
  },
  {
    id: 'comptia-cloud-plus',
    name: 'CompTIA Cloud+',
    provider: 'CompTIA',
    description: 'Validate vendor-neutral skills for deploying, securing, managing, and troubleshooting cloud environments.',
    category: 'cloud',
    difficulty: 'Intermediate',
    duration: '3–5 months',
    costType: 'Paid',
    skills: ['Cloud architecture', 'Deployment', 'Cloud security', 'Operations', 'Troubleshooting'],
    officialUrl: 'https://www.comptia.org/en-us/certifications/cloud/',
    providerLogo: '',
    recommendedCareerPaths: ['cloud-engineer', 'devops', 'network-engineer'],
  },
  {
    id: 'comptia-data-plus',
    name: 'CompTIA Data+',
    provider: 'CompTIA',
    description: 'Demonstrate practical understanding of data mining, analysis, visualisation, governance, and reporting.',
    category: 'data',
    difficulty: 'Intermediate',
    duration: '3–5 months',
    costType: 'Paid',
    skills: ['Data analysis', 'Data visualisation', 'Statistics', 'Data governance', 'Reporting'],
    officialUrl: 'https://www.comptia.org/en-us/certifications/data/',
    providerLogo: '',
    recommendedCareerPaths: ['data-analyst', 'data-engineer', 'data-science'],
  },
];

export const certificationVideos = [
  {
    id: 'video-ai-fundamentals',
    certificationId: 'microsoft-azure-ai-fundamentals',
    title: 'Azure AI Fundamentals Study Cram',
    channel: 'John Savill’s Technical Training',
    youtubeUrl: 'https://www.youtube.com/watch?v=E9aarWMLJw0',
    duration: '2h 5m',
    topic: 'Azure AI fundamentals concept review',
  },
  {
    id: 'video-sc-900',
    certificationId: 'microsoft-security-compliance-identity-fundamentals',
    title: 'SC-900 Security, Compliance, and Identity Study Cram',
    channel: 'John Savill’s Technical Training',
    youtubeUrl: 'https://www.youtube.com/watch?v=Bz-8jM3jg-8',
    duration: '2h 15m',
    topic: 'SC-900 exam domains',
  },
  {
    id: 'video-pl-900',
    certificationId: 'microsoft-power-platform-fundamentals',
    title: 'PL-900 Power Platform Fundamentals Study Cram',
    channel: 'John Savill’s Technical Training',
    youtubeUrl: 'https://www.youtube.com/watch?v=lbPHM-MiEUA',
    duration: '1h 53m',
    topic: 'PL-900 exam domains',
  },
  {
    id: 'video-aws-ai',
    certificationId: 'aws-certified-ai-practitioner',
    title: 'Cloud Computing Explained',
    channel: 'Simplilearn',
    youtubeUrl: 'https://www.youtube.com/watch?v=M988_fsOSWo',
    duration: '6m',
    topic: 'Cloud and AI foundations',
  },
  {
    id: 'video-google-cyber',
    certificationId: 'google-cybersecurity-professional',
    title: 'Cybersecurity for Beginners',
    channel: 'Google Career Certificates',
    youtubeUrl: 'https://www.youtube.com/watch?v=_DVVNOGYtmU',
    duration: '9m',
    topic: 'Cybersecurity foundations',
  },
  {
    id: 'video-google-data',
    certificationId: 'google-advanced-data-analytics',
    title: 'Data Analysis with Python',
    channel: 'freeCodeCamp.org',
    youtubeUrl: 'https://www.youtube.com/watch?v=GPVsHOlRBBI',
    duration: '4h 22m',
    topic: 'Python data analysis',
  },
  {
    id: 'video-ibm-cyber',
    certificationId: 'ibm-cybersecurity-analyst',
    title: 'A Beginner Cybersecurity Roadmap',
    channel: 'Cyber with Ben',
    youtubeUrl: 'https://www.youtube.com/watch?v=b12JrM-6DBY',
    duration: '15m',
    topic: 'Entry-level cybersecurity planning',
  },
  {
    id: 'video-ibm-devops',
    certificationId: 'ibm-devops-software-engineering',
    title: 'Docker Tutorial for Beginners',
    channel: 'TechWorld with Nana',
    youtubeUrl: 'https://www.youtube.com/watch?v=3c-iBn73dDE',
    duration: '2h 46m',
    topic: 'Containers and DevOps',
  },
  {
    id: 'video-github-foundations',
    certificationId: 'github-foundations',
    title: 'Git and GitHub for Beginners',
    channel: 'freeCodeCamp.org',
    youtubeUrl: 'https://www.youtube.com/watch?v=RGOj5yH7evk',
    duration: '1h 8m',
    topic: 'Git and GitHub foundations',
  },
  {
    id: 'video-linux-foundations',
    certificationId: 'linux-foundation-certified-it-associate',
    title: 'Introduction to Linux',
    channel: 'freeCodeCamp.org',
    youtubeUrl: 'https://www.youtube.com/watch?v=sWbUDq4S6Y8',
    duration: '6h 7m',
    topic: 'Linux foundations',
  },
  {
    id: 'video-comptia-cloud',
    certificationId: 'comptia-cloud-plus',
    title: 'Cloud Computing Explained',
    channel: 'Simplilearn',
    youtubeUrl: 'https://www.youtube.com/watch?v=M988_fsOSWo',
    duration: '6m',
    topic: 'Cloud computing foundations',
  },
  {
    id: 'video-comptia-data',
    certificationId: 'comptia-data-plus',
    title: 'Learn Data Science',
    channel: 'freeCodeCamp.org',
    youtubeUrl: 'https://www.youtube.com/watch?v=ua-CiDNNj30',
    duration: '5h 34m',
    topic: 'Data science foundations',
  },
  // Invalid or empty URLs are deliberately ignored by the UI.
  {
    id: 'video-validation-example',
    certificationId: 'comptia-data-plus',
    title: 'Unavailable sample',
    channel: 'Unknown',
    youtubeUrl: '',
    duration: '',
    topic: 'Validation example',
  },
];

export function loadCertificationCatalog() {
  return Promise.resolve(certifications);
}
