// This is the browsable, provider-grouped credential catalog. Some credentials
// also appear inside a relevant roadmap so learners can discover them in context.
export const certificationCategories = {
  ai: 'Artificial Intelligence',
  cloud: 'Cloud Computing',
  data: 'Data and Analytics',
  engineering: 'Software Engineering',
  security: 'Cybersecurity',
  support: 'IT Support',
};

export const certificationProviders = {
  'WeThinkCode_': {
    description: 'South African software development training with a tuition-free main programme and shorter learning tracks.',
    logoUrl: 'https://wethinkcode.co.za/wp-content/uploads/2020/08/W-1.png',
    website: 'https://apply.wethinkcode.co.za/',
  },
  Codecademy: {
    description: 'Guided career paths with projects, assessments, and professional certifications on selected Pro paths.',
    logoUrl: 'https://cdn.simpleicons.org/codecademy',
    website: 'https://www.codecademy.com/catalog',
  },
  Coursera: {
    description: 'Paid and financial-aid-eligible professional certificates from technology companies and universities.',
    logoUrl: 'https://cdn.simpleicons.org/coursera',
    website: 'https://www.coursera.org/professional-certificates',
  },
  Microsoft: {
    description: 'Role-based and fundamentals credentials across Azure, security, data, AI, and business applications.',
    logoUrl: 'https://www.microsoft.com/favicon.ico?v2',
    website: 'https://learn.microsoft.com/en-us/credentials/',
  },
  AWS: {
    description: 'Cloud credentials covering foundational knowledge through specialist and professional practice.',
    logoUrl: 'https://cdn.jsdelivr.net/npm/simple-icons@13.21.0/icons/amazonwebservices.svg',
    website: 'https://aws.amazon.com/certification/',
  },
  Google: {
    description: 'Career certificates and technical credentials for data, cybersecurity, cloud, and digital careers.',
    logoUrl: 'https://cdn.simpleicons.org/google',
    website: 'https://grow.google/certificates/',
  },
  IBM: {
    description: 'Job-focused professional certificates spanning software engineering, data, AI, and cybersecurity.',
    logoUrl: 'https://www.ibm.com/favicon.ico',
    website: 'https://www.ibm.com/training/credentials',
  },
  'Cisco Networking Academy': {
    description: 'Beginner-friendly networking, cybersecurity, programming, and data courses with digital badges.',
    logoUrl: 'https://cdn.simpleicons.org/cisco',
    website: 'https://www.cisco.com/site/us/en/learn/training-certifications/training/netacad/index.html',
  },
  freeCodeCamp: {
    description: 'Free, project-based learning paths that award verified certifications after required projects and exams.',
    logoUrl: 'https://cdn.simpleicons.org/freecodecamp',
    website: 'https://www.freecodecamp.org/learn/',
  },
  GitHub: {
    description: 'Credentials that validate practical knowledge of GitHub products, collaboration, and developer workflows.',
    logoUrl: 'https://cdn.simpleicons.org/github',
    website: 'https://resources.github.com/learn/certifications/',
  },
  'Linux Foundation': {
    description: 'Vendor-neutral, performance-oriented credentials for Linux, cloud, Kubernetes, and open source.',
    logoUrl: 'https://cdn.simpleicons.org/linuxfoundation',
    website: 'https://training.linuxfoundation.org/certification-catalog/',
  },
  CompTIA: {
    description: 'Vendor-neutral IT certifications for support, networking, security, cloud, and data roles.',
    logoUrl: 'https://cdn.simpleicons.org/comptia',
    website: 'https://www.comptia.org/en-us/certifications/',
  },
  'Oracle University': {
    description: 'Technical certifications for Java, Oracle Cloud Infrastructure, AI, databases, and enterprise platforms.',
    logoUrl: 'https://www.oracle.com/favicon.ico',
    website: 'https://education.oracle.com/certification/index.html',
  },
  ISC2: {
    description: 'Vendor-neutral cybersecurity certifications from entry-level foundations through specialist and leadership roles.',
    logoUrl: 'https://cdn.simpleicons.org/isc2',
    website: 'https://www.isc2.org/certifications',
  },
};

export const certifications = [
  {
    id: 'microsoft-azure-ai-fundamentals',
    name: 'Microsoft Certified: Azure AI Fundamentals',
    provider: 'Microsoft',
    description: 'Validate foundational knowledge of AI workloads, machine learning, generative AI, and Azure AI services.',
    category: 'ai',
    difficulty: 'Beginner',
    duration: '4–6 weeks',
    costType: 'Paid',
    skills: ['AI workloads', 'Machine learning concepts', 'Generative AI', 'Azure AI services'],
    officialUrl: 'https://learn.microsoft.com/en-us/credentials/certifications/azure-ai-fundamentals/',
    providerLogo: '',
    recommendedCareerPaths: ['ai-engineer', 'ml-engineer', 'data-science'],
  },
  {
    id: 'microsoft-security-compliance-identity-fundamentals',
    name: 'Microsoft Security, Compliance, and Identity Fundamentals',
    provider: 'Microsoft',
    description: 'Build a grounding in Zero Trust, Microsoft Entra, security solutions, compliance, and identity concepts.',
    category: 'security',
    difficulty: 'Beginner',
    duration: '4–6 weeks',
    costType: 'Paid',
    skills: ['Zero Trust', 'Identity concepts', 'Microsoft Entra', 'Compliance fundamentals'],
    officialUrl:
      'https://learn.microsoft.com/en-us/credentials/certifications/security-compliance-and-identity-fundamentals/',
    providerLogo: '',
    recommendedCareerPaths: ['cybersecurity', 'it-support-specialist', 'cloud-engineer'],
  },
  {
    id: 'microsoft-power-platform-fundamentals',
    name: 'Microsoft Certified: Power Platform Fundamentals',
    provider: 'Microsoft',
    description: 'Learn how low-code tools, Dataverse, Power Apps, and Power Automate support business solutions.',
    category: 'engineering',
    difficulty: 'Beginner',
    duration: '4–6 weeks',
    costType: 'Paid',
    skills: ['Power Apps', 'Power Automate', 'Dataverse', 'Low-code solution design'],
    officialUrl: 'https://learn.microsoft.com/en-us/credentials/certifications/power-platform-fundamentals/',
    providerLogo: '',
    recommendedCareerPaths: ['fullstack-dev', 'data-analyst', 'it-support-specialist'],
  },
  {
    id: 'aws-certified-ai-practitioner',
    name: 'AWS Certified AI Practitioner',
    provider: 'AWS',
    description: 'Demonstrate foundational understanding of AI, machine learning, generative AI, and responsible AI on AWS.',
    category: 'ai',
    difficulty: 'Beginner',
    duration: '6–8 weeks',
    costType: 'Paid',
    skills: ['AI and ML concepts', 'Generative AI', 'Responsible AI', 'AWS AI services'],
    officialUrl: 'https://aws.amazon.com/certification/certified-ai-practitioner/',
    providerLogo: '',
    recommendedCareerPaths: ['ai-engineer', 'cloud-engineer', 'data-science'],
  },
  {
    id: 'google-cybersecurity-professional',
    name: 'Google Cybersecurity Professional Certificate',
    provider: 'Google',
    description: 'Prepare for entry-level security work through hands-on Linux, SQL, Python, SIEM, and incident-response practice.',
    category: 'security',
    difficulty: 'Beginner',
    duration: 'Up to 6 months',
    costType: 'Financial Aid Available',
    skills: ['Linux', 'SQL', 'Python', 'SIEM', 'Incident response'],
    officialUrl: 'https://www.coursera.org/professional-certificates/google-cybersecurity',
    providerLogo: '',
    recommendedCareerPaths: ['cybersecurity', 'network-technician', 'it-support-specialist'],
  },
  {
    id: 'google-advanced-data-analytics',
    name: 'Google Advanced Data Analytics Professional Certificate',
    provider: 'Google',
    description: 'Advance from analysis into statistics, regression, machine learning, and stakeholder-ready data storytelling.',
    category: 'data',
    difficulty: 'Intermediate',
    duration: 'Up to 6 months',
    costType: 'Financial Aid Available',
    skills: ['Statistics', 'Regression analysis', 'Python', 'Machine learning', 'Data storytelling'],
    officialUrl: 'https://www.coursera.org/professional-certificates/google-advanced-data-analytics',
    providerLogo: '',
    recommendedCareerPaths: ['data-analyst', 'data-science', 'ml-engineer'],
  },
  {
    id: 'ibm-cybersecurity-analyst',
    name: 'IBM Cybersecurity Analyst Professional Certificate',
    provider: 'IBM',
    description: 'Develop practical security operations, threat intelligence, incident response, and job-search skills.',
    category: 'security',
    difficulty: 'Beginner',
    duration: '4–8 months',
    costType: 'Financial Aid Available',
    skills: ['Security operations', 'Threat intelligence', 'Incident response', 'Network security'],
    officialUrl: 'https://www.coursera.org/professional-certificates/ibm-cybersecurity-analyst',
    providerLogo: '',
    recommendedCareerPaths: ['cybersecurity', 'network-engineer', 'it-support-specialist'],
  },
  {
    id: 'ibm-devops-software-engineering',
    name: 'IBM DevOps and Software Engineering Professional Certificate',
    provider: 'IBM',
    description: 'Build job-ready skills across Python, Linux, containers, Kubernetes, microservices, testing, and CI/CD.',
    category: 'engineering',
    difficulty: 'Beginner',
    duration: '6 months',
    costType: 'Financial Aid Available',
    skills: ['Python', 'Linux', 'Docker', 'Kubernetes', 'CI/CD', 'Microservices'],
    officialUrl: 'https://www.coursera.org/professional-certificates/devops-and-software-engineering',
    providerLogo: '',
    recommendedCareerPaths: ['devops', 'backend-dev', 'cloud-engineer'],
  },
  {
    id: 'github-foundations',
    name: 'GitHub Foundations Certification',
    provider: 'GitHub',
    description: 'Validate foundational Git, repository, collaboration, and GitHub product knowledge.',
    category: 'engineering',
    difficulty: 'Beginner',
    duration: '3–5 weeks',
    costType: 'Paid',
    skills: ['Git basics', 'Repositories', 'Collaboration', 'Branches and pull requests'],
    officialUrl:
      'https://docs.github.com/en/get-started/showcase-your-expertise-with-github-certifications/about-github-certifications',
    providerLogo: '',
    recommendedCareerPaths: ['frontend-dev', 'backend-dev', 'fullstack-dev', 'devops'],
  },
  {
    id: 'linux-foundation-certified-it-associate',
    name: 'Linux Foundation Certified IT Associate',
    provider: 'Linux Foundation',
    description: 'Confirm broad entry-level knowledge of Linux, cloud, networking, security, DevOps, and IT operations.',
    category: 'support',
    difficulty: 'Beginner',
    duration: '3–6 months',
    costType: 'Paid',
    skills: ['Linux', 'System administration', 'Networking', 'Cloud fundamentals', 'DevOps basics'],
    officialUrl: 'https://training.linuxfoundation.org/certification/certified-it-associate/',
    providerLogo: '',
    recommendedCareerPaths: ['it-support-specialist', 'network-technician', 'devops', 'cloud-engineer'],
  },
  {
    id: 'comptia-cloud-plus',
    name: 'CompTIA Cloud+',
    provider: 'CompTIA',
    description: 'Validate vendor-neutral skills for deploying, securing, managing, and troubleshooting cloud environments.',
    category: 'cloud',
    difficulty: 'Intermediate',
    duration: '3–5 months',
    costType: 'Paid',
    skills: ['Cloud architecture', 'Deployment', 'Cloud security', 'Operations', 'Troubleshooting'],
    officialUrl: 'https://www.comptia.org/en-us/certifications/cloud/',
    providerLogo: '',
    recommendedCareerPaths: ['cloud-engineer', 'devops', 'network-engineer'],
  },
  {
    id: 'comptia-data-plus',
    name: 'CompTIA Data+',
    provider: 'CompTIA',
    description: 'Demonstrate practical understanding of data mining, analysis, visualisation, governance, and reporting.',
    category: 'data',
    difficulty: 'Intermediate',
    duration: '3–5 months',
    costType: 'Paid',
    skills: ['Data analysis', 'Data visualisation', 'Statistics', 'Data governance', 'Reporting'],
    officialUrl: 'https://www.comptia.org/en-us/certifications/data/',
    providerLogo: '',
    recommendedCareerPaths: ['data-analyst', 'data-engineer', 'data-science'],
  },
  {
    id: 'wethinkcode-main-programme',
    name: 'Software Development Main Programme',
    provider: 'WeThinkCode_',
    credentialType: 'Tuition-free programme',
    description: 'A selective two-year programme combining software development, problem solving, teamwork, and work readiness.',
    category: 'engineering',
    difficulty: 'Beginner',
    duration: '2 years',
    costType: 'Free',
    skills: ['Software development', 'Problem solving', 'Teamwork', 'Work readiness'],
    officialUrl: 'https://apply.wethinkcode.co.za/',
    providerLogo: '',
    recommendedCareerPaths: ['frontend-dev', 'backend-dev', 'fullstack-dev'],
  },
  {
    id: 'wethinkcode-idc-short-courses',
    name: 'Innovation Development Centre Short Courses',
    provider: 'WeThinkCode_',
    credentialType: 'Short-course programme',
    description: 'Short learning tracks that introduce coding foundations alongside practical work-readiness workshops.',
    category: 'engineering',
    difficulty: 'Beginner',
    duration: 'Short course',
    costType: 'Varies',
    skills: ['Coding basics', 'Digital skills', 'Career preparation', 'Collaboration'],
    officialUrl: 'https://apply.wethinkcode.co.za/',
    providerLogo: '',
    recommendedCareerPaths: ['frontend-dev', 'backend-dev', 'it-support-specialist'],
  },
  {
    id: 'codecademy-full-stack-professional',
    name: 'Full-Stack Engineer Professional Certification',
    provider: 'Codecademy',
    credentialType: 'Professional certification',
    description: 'Build and assess front-end, back-end, database, testing, deployment, and portfolio-ready development skills.',
    category: 'engineering',
    difficulty: 'Beginner',
    duration: '150 hours',
    costType: 'Paid',
    skills: ['HTML and CSS', 'JavaScript', 'React', 'Node.js', 'SQL'],
    officialUrl: 'https://www.codecademy.com/learn/paths/full-stack-engineer-career-path',
    providerLogo: '',
    recommendedCareerPaths: ['fullstack-dev', 'frontend-dev', 'backend-dev'],
  },
  {
    id: 'codecademy-front-end-professional',
    name: 'Front-End Engineer Professional Certification',
    provider: 'Codecademy',
    credentialType: 'Professional certification',
    description: 'Develop and validate browser, accessibility, responsive design, JavaScript, React, and testing skills.',
    category: 'engineering',
    difficulty: 'Beginner',
    duration: '115 hours',
    costType: 'Paid',
    skills: ['HTML', 'CSS', 'JavaScript', 'React', 'Accessibility'],
    officialUrl: 'https://www.codecademy.com/learn/paths/front-end-engineer-career-path',
    providerLogo: '',
    recommendedCareerPaths: ['frontend-dev', 'fullstack-dev'],
  },
  {
    id: 'codecademy-back-end-professional',
    name: 'Back-End Engineer Professional Certification',
    provider: 'Codecademy',
    credentialType: 'Professional certification',
    description: 'Learn server-side programming, APIs, databases, security, scalability, and software design principles.',
    category: 'engineering',
    difficulty: 'Beginner',
    duration: '100+ hours',
    costType: 'Paid',
    skills: ['Node.js', 'APIs', 'Databases', 'Security', 'Scalability'],
    officialUrl: 'https://www.codecademy.com/learn/paths/back-end-engineer-career-path',
    providerLogo: '',
    recommendedCareerPaths: ['backend-dev', 'fullstack-dev'],
  },
  {
    id: 'codecademy-computer-science-professional',
    name: 'Computer Science Professional Certification',
    provider: 'Codecademy',
    credentialType: 'Professional certification',
    description: 'Build a practical computer science foundation through Python, data structures, algorithms, and projects.',
    category: 'engineering',
    difficulty: 'Beginner',
    duration: '75 hours',
    costType: 'Paid',
    skills: ['Python', 'Data structures', 'Algorithms', 'Computer science'],
    officialUrl: 'https://www.codecademy.com/learn/paths/computer-science',
    providerLogo: '',
    recommendedCareerPaths: ['backend-dev', 'fullstack-dev', 'data-science'],
  },
  {
    id: 'codecademy-data-science-ml-professional',
    name: 'Data Scientist: Machine Learning Professional Certification',
    provider: 'Codecademy',
    credentialType: 'Professional certification',
    description: 'Apply Python, SQL, statistics, scikit-learn, and neural networks to portfolio-ready data projects.',
    category: 'data',
    difficulty: 'Beginner',
    duration: '95 hours',
    costType: 'Paid',
    skills: ['Python', 'SQL', 'Machine learning', 'Statistics', 'TensorFlow'],
    officialUrl: 'https://www.codecademy.com/learn/paths/data-science',
    providerLogo: '',
    recommendedCareerPaths: ['data-science', 'ml-engineer', 'data-analyst'],
  },
  {
    id: 'codecademy-data-science-analytics-professional',
    name: 'Data Scientist: Analytics Professional Certification',
    provider: 'Codecademy',
    credentialType: 'Professional certification',
    description: 'Use Python and SQL to query, analyse, visualise, and communicate insights from real datasets.',
    category: 'data',
    difficulty: 'Beginner',
    duration: '70 hours',
    costType: 'Paid',
    skills: ['Python', 'SQL', 'Data analysis', 'Visualisation', 'Communication'],
    officialUrl: 'https://www.codecademy.com/catalog/subject/data-science',
    providerLogo: '',
    recommendedCareerPaths: ['data-analyst', 'data-science'],
  },
  {
    id: 'cisco-junior-cybersecurity-analyst-path',
    name: 'Junior Cybersecurity Analyst Career Path',
    provider: 'Cisco Networking Academy',
    credentialType: 'Career path and badge',
    description: 'Prepare for entry-level security operations through threat analysis, endpoint security, and network defence.',
    category: 'security',
    difficulty: 'Beginner',
    duration: 'Self-paced',
    costType: 'Free',
    skills: ['Network defence', 'Endpoint security', 'Threat analysis', 'Security operations'],
    officialUrl: 'https://www.cisco.com/site/us/en/learn/training-certifications/training/netacad/index.html',
    providerLogo: '',
    recommendedCareerPaths: ['cybersecurity', 'network-technician'],
  },
  {
    id: 'cisco-networking-basics-badge',
    name: 'Networking Basics',
    provider: 'Cisco Networking Academy',
    credentialType: 'Course badge',
    description: 'Learn how networks operate, how devices communicate, and how to configure foundational connectivity.',
    category: 'support',
    difficulty: 'Beginner',
    duration: '22 hours',
    costType: 'Free',
    skills: ['Networking', 'IP addressing', 'Network devices', 'Connectivity'],
    officialUrl: 'https://www.cisco.com/site/us/en/learn/training-certifications/training/netacad/index.html',
    providerLogo: '',
    recommendedCareerPaths: ['network-technician', 'network-engineer', 'it-support-specialist'],
  },
  {
    id: 'cisco-python-essentials-one-badge',
    name: 'Python Essentials 1',
    provider: 'Cisco Networking Academy',
    credentialType: 'Course badge',
    description: 'Build programming foundations with Python syntax, control flow, functions, collections, and debugging.',
    category: 'engineering',
    difficulty: 'Beginner',
    duration: '30 hours',
    costType: 'Free',
    skills: ['Python', 'Programming fundamentals', 'Functions', 'Debugging'],
    officialUrl: 'https://www.cisco.com/site/us/en/learn/training-certifications/training/netacad/index.html',
    providerLogo: '',
    recommendedCareerPaths: ['backend-dev', 'data-analyst', 'cybersecurity'],
  },
  {
    id: 'cisco-data-analytics-essentials-badge',
    name: 'Data Analytics Essentials',
    provider: 'Cisco Networking Academy',
    credentialType: 'Course badge',
    description: 'Learn the essential tools and practices used to transform, analyse, and present data.',
    category: 'data',
    difficulty: 'Beginner',
    duration: '30 hours',
    costType: 'Free',
    skills: ['Data analysis', 'Data preparation', 'Visualisation', 'Analytics tools'],
    officialUrl: 'https://www.cisco.com/site/us/en/learn/training-certifications/training/netacad/index.html',
    providerLogo: '',
    recommendedCareerPaths: ['data-analyst', 'data-science'],
  },
  {
    id: 'freecodecamp-relational-database',
    name: 'Relational Database Certification',
    provider: 'freeCodeCamp',
    credentialType: 'Verified certification',
    description: 'Practise Linux, Bash, Git, PostgreSQL, and SQL by completing command-line projects.',
    category: 'data',
    difficulty: 'Beginner',
    duration: 'Self-paced',
    costType: 'Free',
    skills: ['PostgreSQL', 'SQL', 'Bash', 'Git', 'Linux'],
    officialUrl: 'https://www.freecodecamp.org/learn/relational-database/',
    providerLogo: '',
    recommendedCareerPaths: ['data-engineer', 'backend-dev', 'data-analyst'],
  },
  {
    id: 'freecodecamp-data-analysis-python',
    name: 'Data Analysis with Python Certification',
    provider: 'freeCodeCamp',
    credentialType: 'Verified certification',
    description: 'Complete practical projects using NumPy, pandas, Matplotlib, and data-analysis workflows.',
    category: 'data',
    difficulty: 'Intermediate',
    duration: 'Self-paced',
    costType: 'Free',
    skills: ['Python', 'NumPy', 'pandas', 'Matplotlib', 'Data analysis'],
    officialUrl: 'https://www.freecodecamp.org/learn/data-analysis-with-python/',
    providerLogo: '',
    recommendedCareerPaths: ['data-analyst', 'data-science'],
  },
  {
    id: 'freecodecamp-information-security',
    name: 'Information Security Certification',
    provider: 'freeCodeCamp',
    credentialType: 'Verified certification',
    description: 'Build secure web applications and complete projects covering penetration testing and information assurance.',
    category: 'security',
    difficulty: 'Intermediate',
    duration: 'Self-paced',
    costType: 'Free',
    skills: ['Application security', 'Penetration testing', 'Python', 'Secure development'],
    officialUrl: 'https://www.freecodecamp.org/learn/information-security/',
    providerLogo: '',
    recommendedCareerPaths: ['cybersecurity', 'backend-dev'],
  },
  {
    id: 'freecodecamp-machine-learning-python',
    name: 'Machine Learning with Python Certification',
    provider: 'freeCodeCamp',
    credentialType: 'Verified certification',
    description: 'Complete project-based exercises in neural networks, computer vision, NLP, and reinforcement learning.',
    category: 'ai',
    difficulty: 'Intermediate',
    duration: 'Self-paced',
    costType: 'Free',
    skills: ['Python', 'TensorFlow', 'Neural networks', 'NLP', 'Computer vision'],
    officialUrl: 'https://www.freecodecamp.org/learn/machine-learning-with-python/',
    providerLogo: '',
    recommendedCareerPaths: ['ml-engineer', 'ai-engineer', 'data-science'],
  },
  {
    id: 'oracle-oci-ai-foundations-associate',
    name: 'OCI AI Foundations Associate',
    provider: 'Oracle University',
    credentialType: 'Associate certification',
    description: 'Validate foundational AI, machine learning, generative AI, and Oracle Cloud AI service knowledge.',
    category: 'ai',
    difficulty: 'Beginner',
    duration: 'Self-paced',
    costType: 'Paid',
    skills: ['AI foundations', 'Machine learning', 'Generative AI', 'OCI AI services'],
    officialUrl: 'https://education.oracle.com/certification/index.html',
    providerLogo: '',
    recommendedCareerPaths: ['ai-engineer', 'cloud-engineer', 'data-science'],
  },
  {
    id: 'oracle-oci-foundations-associate',
    name: 'OCI Foundations Associate',
    provider: 'Oracle University',
    credentialType: 'Associate certification',
    description: 'Validate core cloud concepts, OCI services, security, pricing, support, and operations knowledge.',
    category: 'cloud',
    difficulty: 'Beginner',
    duration: 'Self-paced',
    costType: 'Paid',
    skills: ['Cloud concepts', 'OCI services', 'Cloud security', 'Operations'],
    officialUrl: 'https://education.oracle.com/certification/index.html',
    providerLogo: '',
    recommendedCareerPaths: ['cloud-engineer', 'devops', 'it-support-specialist'],
  },
  {
    id: 'oracle-oci-architect-associate',
    name: 'OCI Architect Associate',
    provider: 'Oracle University',
    credentialType: 'Associate certification',
    description: 'Demonstrate the ability to design secure, resilient, and scalable workloads on Oracle Cloud Infrastructure.',
    category: 'cloud',
    difficulty: 'Intermediate',
    duration: 'Self-paced',
    costType: 'Paid',
    skills: ['Cloud architecture', 'Networking', 'Identity', 'Resilience', 'Cost management'],
    officialUrl: 'https://education.oracle.com/certification/index.html',
    providerLogo: '',
    recommendedCareerPaths: ['cloud-engineer', 'devops'],
  },
  {
    id: 'oracle-java-se-21-developer-professional',
    name: 'Java SE 21 Developer Professional',
    provider: 'Oracle University',
    credentialType: 'Professional certification',
    description: 'Validate professional Java development knowledge using the language, APIs, object-oriented design, and modern features.',
    category: 'engineering',
    difficulty: 'Advanced',
    duration: 'Self-paced',
    costType: 'Paid',
    skills: ['Java 21', 'Object-oriented design', 'Java APIs', 'Concurrency'],
    officialUrl: 'https://education.oracle.com/java-se-21-developer-certified-professional/trackp_JSE21OCP',
    providerLogo: '',
    recommendedCareerPaths: ['backend-dev', 'fullstack-dev'],
  },
  {
    id: 'coursera-meta-front-end-developer',
    name: 'Meta Front-End Developer Professional Certificate',
    provider: 'Coursera',
    credentialType: 'Professional certificate',
    description: 'Build job-ready front-end skills with HTML, CSS, JavaScript, React, version control, and portfolio projects.',
    category: 'engineering',
    difficulty: 'Beginner',
    duration: 'About 7 months',
    costType: 'Financial Aid Available',
    skills: ['HTML', 'CSS', 'JavaScript', 'React', 'Git'],
    officialUrl: 'https://www.coursera.org/professional-certificates/meta-front-end-developer',
    recommendedCareerPaths: ['frontend-dev', 'fullstack-dev'],
  },
  {
    id: 'coursera-meta-back-end-developer',
    name: 'Meta Back-End Developer Professional Certificate',
    provider: 'Coursera',
    credentialType: 'Professional certificate',
    description: 'Prepare for back-end roles using Python, Django, APIs, SQL, Git, Linux, and a capstone application.',
    category: 'engineering',
    difficulty: 'Beginner',
    duration: 'About 8 months',
    costType: 'Financial Aid Available',
    skills: ['Python', 'Django', 'REST APIs', 'SQL', 'Git'],
    officialUrl: 'https://www.coursera.org/professional-certificates/meta-back-end-developer',
    recommendedCareerPaths: ['backend-dev', 'fullstack-dev'],
  },
  {
    id: 'coursera-microsoft-full-stack-developer',
    name: 'Microsoft Full-Stack Developer Professional Certificate',
    provider: 'Coursera',
    credentialType: 'Professional certificate',
    description: 'Develop full-stack applications with C#, .NET, ASP.NET, SQL, Azure DevOps, security, and CI/CD.',
    category: 'engineering',
    difficulty: 'Beginner',
    duration: 'About 9 months',
    costType: 'Financial Aid Available',
    skills: ['C#', '.NET', 'ASP.NET', 'SQL', 'Azure DevOps'],
    officialUrl: 'https://www.coursera.org/professional-certificates/microsoft-full-stack-developer',
    recommendedCareerPaths: ['fullstack-dev', 'backend-dev', 'devops'],
  },
  {
    id: 'coursera-ibm-front-end-developer',
    name: 'IBM Front-End Developer Professional Certificate',
    provider: 'Coursera',
    credentialType: 'Professional certificate',
    description: 'Learn responsive development, React, UI and UX foundations, cloud-native practices, testing, and deployment.',
    category: 'engineering',
    difficulty: 'Beginner',
    duration: 'About 4 months',
    costType: 'Financial Aid Available',
    skills: ['HTML', 'CSS', 'JavaScript', 'React', 'UI/UX'],
    officialUrl: 'https://www.coursera.org/professional-certificates/ibm-frontend-developer',
    recommendedCareerPaths: ['frontend-dev', 'fullstack-dev'],
  },
  {
    id: 'coursera-ibm-data-engineering',
    name: 'IBM Data Engineering Professional Certificate',
    provider: 'Coursera',
    credentialType: 'Professional certificate',
    description: 'Build data engineering foundations across SQL, ETL, warehouses, NoSQL, Spark, Airflow, and Kafka.',
    category: 'data',
    difficulty: 'Beginner',
    duration: 'About 6 months',
    costType: 'Financial Aid Available',
    skills: ['Python', 'SQL', 'ETL', 'Apache Spark', 'Data pipelines'],
    officialUrl: 'https://www.coursera.org/professional-certificates/ibm-data-engineer',
    recommendedCareerPaths: ['data-engineer', 'data-analyst', 'data-science'],
  },
  {
    id: 'coursera-deeplearning-ai-machine-learning',
    name: 'Machine Learning Specialization',
    provider: 'Coursera',
    credentialType: 'Specialization certificate',
    description: 'Learn practical machine learning with Python, scikit-learn, TensorFlow, neural networks, and decision trees.',
    category: 'ai',
    difficulty: 'Beginner',
    duration: 'About 2 months',
    costType: 'Financial Aid Available',
    skills: ['Python', 'scikit-learn', 'TensorFlow', 'Neural networks', 'Machine learning'],
    officialUrl: 'https://www.coursera.org/specializations/machine-learning-introduction',
    recommendedCareerPaths: ['ml-engineer', 'ai-engineer', 'data-science'],
  },
  {
    id: 'cisco-ccst-cybersecurity',
    name: 'Cisco Certified Support Technician Cybersecurity',
    provider: 'Cisco Networking Academy',
    credentialType: 'Entry-level certification',
    description: 'Validate entry-level security principles, endpoint and network security, risk, and incident-handling knowledge.',
    category: 'security',
    difficulty: 'Beginner',
    duration: 'Self-paced exam preparation',
    costType: 'Paid',
    skills: ['Security principles', 'Endpoint security', 'Risk management', 'Incident handling'],
    officialUrl: 'https://www.cisco.com/site/us/en/learn/training-certifications/certifications/support-technician/index.html',
    recommendedCareerPaths: ['cybersecurity', 'it-support-specialist'],
  },
  {
    id: 'cisco-ccst-networking',
    name: 'Cisco Certified Support Technician Networking',
    provider: 'Cisco Networking Academy',
    credentialType: 'Entry-level certification',
    description: 'Validate foundational knowledge of network devices, media, protocols, addressing, and troubleshooting.',
    category: 'support',
    difficulty: 'Beginner',
    duration: 'Self-paced exam preparation',
    costType: 'Paid',
    skills: ['Networking', 'Protocols', 'IP addressing', 'Troubleshooting'],
    officialUrl: 'https://www.cisco.com/site/us/en/learn/training-certifications/certifications/support-technician/index.html',
    recommendedCareerPaths: ['network-technician', 'network-engineer', 'it-support-specialist'],
  },
  {
    id: 'cisco-ccst-it-support',
    name: 'Cisco Certified Support Technician IT Support',
    provider: 'Cisco Networking Academy',
    credentialType: 'Entry-level certification',
    description: 'Demonstrate work-ready skills for help desk, end-user support, computer support, and troubleshooting roles.',
    category: 'support',
    difficulty: 'Beginner',
    duration: 'Self-paced exam preparation',
    costType: 'Paid',
    skills: ['IT support', 'Help desk', 'Troubleshooting', 'End-user support'],
    officialUrl: 'https://www.cisco.com/site/us/en/learn/training-certifications/certifications/support-technician/index.html',
    recommendedCareerPaths: ['it-support-specialist', 'network-technician'],
  },
  {
    id: 'cisco-ccna',
    name: 'Cisco Certified Network Associate (CCNA)',
    provider: 'Cisco Networking Academy',
    credentialType: 'Associate certification',
    description: 'Validate network fundamentals, IP connectivity, services, security fundamentals, automation, and programmability.',
    category: 'cloud',
    difficulty: 'Intermediate',
    duration: 'Self-paced exam preparation',
    costType: 'Paid',
    skills: ['Network fundamentals', 'IP connectivity', 'Security', 'Automation'],
    officialUrl: 'https://www.cisco.com/site/us/en/learn/training-certifications/certifications/enterprise/ccna/index.html',
    recommendedCareerPaths: ['network-engineer', 'network-technician', 'cloud-engineer'],
  },
  {
    id: 'cisco-ccna-cybersecurity',
    name: 'CCNA Cybersecurity',
    provider: 'Cisco Networking Academy',
    credentialType: 'Associate certification',
    description: 'Validate security monitoring, host analysis, network intrusion analysis, and incident response skills.',
    category: 'security',
    difficulty: 'Intermediate',
    duration: 'Self-paced exam preparation',
    costType: 'Paid',
    skills: ['Security monitoring', 'Host analysis', 'Intrusion analysis', 'Incident response'],
    officialUrl: 'https://www.cisco.com/site/us/en/learn/training-certifications/certifications/cybersecurity/ccna-cybersecurity/index.html',
    recommendedCareerPaths: ['cybersecurity', 'network-engineer'],
  },
  {
    id: 'cisco-devnet-associate',
    name: 'Cisco Certified DevNet Associate',
    provider: 'Cisco Networking Academy',
    credentialType: 'Associate certification',
    description: 'Validate software design, API use, Cisco platform development, application security, and infrastructure automation.',
    category: 'engineering',
    difficulty: 'Intermediate',
    duration: 'Self-paced exam preparation',
    costType: 'Paid',
    skills: ['APIs', 'Software development', 'Automation', 'Application security'],
    officialUrl: 'https://www.cisco.com/site/us/en/learn/training-certifications/exams/index.html',
    recommendedCareerPaths: ['devops', 'backend-dev', 'network-engineer'],
  },
  {
    id: 'cisco-ethical-hacking-certificate',
    name: 'Cisco Certificate in Ethical Hacking',
    provider: 'Cisco Networking Academy',
    credentialType: 'Professional certificate',
    description: 'Complete ethical-hacking training and a hands-on Capture the Flag challenge to demonstrate offensive security skills.',
    category: 'security',
    difficulty: 'Intermediate',
    duration: 'Self-paced',
    costType: 'Varies',
    skills: ['Ethical hacking', 'Penetration testing', 'Red teaming', 'Vulnerability assessment'],
    officialUrl: 'https://www.cisco.com/site/us/en/learn/training-certifications/certifications/ethical-hacker/index.html',
    recommendedCareerPaths: ['cybersecurity'],
  },
  {
    id: 'comptia-a-plus',
    name: 'CompTIA A+',
    provider: 'CompTIA',
    credentialType: 'Industry certification',
    description: 'Validate foundational hardware, operating system, networking, security, troubleshooting, and support skills.',
    category: 'support',
    difficulty: 'Beginner',
    duration: 'Self-paced exam preparation',
    costType: 'Paid',
    skills: ['Hardware', 'Operating systems', 'Troubleshooting', 'IT support'],
    officialUrl: 'https://www.comptia.org/en-us/certifications/a/',
    recommendedCareerPaths: ['it-support-specialist', 'network-technician'],
  },
  {
    id: 'comptia-network-plus',
    name: 'CompTIA Network+',
    provider: 'CompTIA',
    credentialType: 'Industry certification',
    description: 'Validate vendor-neutral networking concepts, implementation, operations, security, and troubleshooting.',
    category: 'support',
    difficulty: 'Beginner',
    duration: 'Self-paced exam preparation',
    costType: 'Paid',
    skills: ['Networking', 'Network operations', 'Network security', 'Troubleshooting'],
    officialUrl: 'https://www.comptia.org/en-us/certifications/network/',
    recommendedCareerPaths: ['network-technician', 'network-engineer', 'it-support-specialist'],
  },
  {
    id: 'comptia-security-plus',
    name: 'CompTIA Security+',
    provider: 'CompTIA',
    credentialType: 'Industry certification',
    description: 'Validate core security operations, threats, architecture, identity, risk, and cryptography knowledge.',
    category: 'security',
    difficulty: 'Beginner',
    duration: 'Self-paced exam preparation',
    costType: 'Paid',
    skills: ['Threats', 'Security operations', 'Identity', 'Risk management', 'Cryptography'],
    officialUrl: 'https://www.comptia.org/en-us/certifications/security/',
    recommendedCareerPaths: ['cybersecurity', 'network-engineer'],
  },
  {
    id: 'linux-foundation-kcna',
    name: 'Kubernetes and Cloud Native Associate (KCNA)',
    provider: 'Linux Foundation',
    credentialType: 'Associate certification',
    description: 'Demonstrate foundational knowledge of Kubernetes, container orchestration, cloud native architecture, and observability.',
    category: 'cloud',
    difficulty: 'Beginner',
    duration: 'Self-paced exam preparation',
    costType: 'Paid',
    skills: ['Kubernetes', 'Containers', 'Cloud native', 'Observability'],
    officialUrl: 'https://training.linuxfoundation.org/certification/kubernetes-cloud-native-associate/',
    recommendedCareerPaths: ['cloud-engineer', 'devops'],
  },
  {
    id: 'linux-foundation-cka',
    name: 'Certified Kubernetes Administrator (CKA)',
    provider: 'Linux Foundation',
    credentialType: 'Performance-based certification',
    description: 'Prove practical Kubernetes administration skills through a command-line, performance-based examination.',
    category: 'cloud',
    difficulty: 'Intermediate',
    duration: 'Self-paced exam preparation',
    costType: 'Paid',
    skills: ['Kubernetes administration', 'Clusters', 'Networking', 'Troubleshooting'],
    officialUrl: 'https://training.linuxfoundation.org/certification/certified-kubernetes-administrator-cka/',
    recommendedCareerPaths: ['cloud-engineer', 'devops'],
  },
  {
    id: 'linux-foundation-ckad',
    name: 'Certified Kubernetes Application Developer (CKAD)',
    provider: 'Linux Foundation',
    credentialType: 'Performance-based certification',
    description: 'Prove the ability to design, build, configure, and expose cloud-native applications for Kubernetes.',
    category: 'engineering',
    difficulty: 'Intermediate',
    duration: 'Self-paced exam preparation',
    costType: 'Paid',
    skills: ['Kubernetes', 'Cloud-native applications', 'Containers', 'Application configuration'],
    officialUrl: 'https://training.linuxfoundation.org/certification/certified-kubernetes-application-developer-ckad/',
    recommendedCareerPaths: ['devops', 'backend-dev', 'cloud-engineer'],
  },
  {
    id: 'linux-foundation-cks',
    name: 'Certified Kubernetes Security Specialist (CKS)',
    provider: 'Linux Foundation',
    credentialType: 'Performance-based certification',
    description: 'Demonstrate advanced Kubernetes and cloud-native security skills after earning the CKA credential.',
    category: 'security',
    difficulty: 'Advanced',
    duration: 'Self-paced exam preparation',
    costType: 'Paid',
    skills: ['Kubernetes security', 'Cluster hardening', 'Supply-chain security', 'Runtime security'],
    officialUrl: 'https://training.linuxfoundation.org/certification/certified-kubernetes-security-specialist/',
    recommendedCareerPaths: ['cybersecurity', 'devops', 'cloud-engineer'],
  },
  {
    id: 'isc2-certified-in-cybersecurity',
    name: 'Certified in Cybersecurity (CC)',
    provider: 'ISC2',
    credentialType: 'Entry-level certification',
    description: 'Validate foundational security principles, access controls, network security, incident response, and operations.',
    category: 'security',
    difficulty: 'Beginner',
    duration: 'Self-paced exam preparation',
    costType: 'Varies',
    skills: ['Security principles', 'Access controls', 'Network security', 'Incident response'],
    officialUrl: 'https://www.isc2.org/certifications/cc',
    recommendedCareerPaths: ['cybersecurity', 'it-support-specialist'],
  },
  {
    id: 'isc2-sscp',
    name: 'Systems Security Certified Practitioner (SSCP)',
    provider: 'ISC2',
    credentialType: 'Professional certification',
    description: 'Validate hands-on skills for monitoring, administering, and defending systems in security operations roles.',
    category: 'security',
    difficulty: 'Intermediate',
    duration: 'Self-paced exam preparation',
    costType: 'Paid',
    skills: ['Security operations', 'Access controls', 'Risk identification', 'Systems security'],
    officialUrl: 'https://www.isc2.org/certifications/sscp',
    recommendedCareerPaths: ['cybersecurity'],
  },
  {
    id: 'isc2-cissp',
    name: 'Certified Information Systems Security Professional (CISSP)',
    provider: 'ISC2',
    credentialType: 'Advanced professional certification',
    description: 'Validate broad security strategy, architecture, engineering, risk management, and leadership expertise.',
    category: 'security',
    difficulty: 'Advanced',
    duration: 'Experience requirement applies',
    costType: 'Paid',
    skills: ['Security architecture', 'Risk management', 'Security operations', 'Leadership'],
    officialUrl: 'https://www.isc2.org/certifications/cissp',
    recommendedCareerPaths: ['cybersecurity'],
  },
  {
    id: 'isc2-ccsp',
    name: 'Certified Cloud Security Professional (CCSP)',
    provider: 'ISC2',
    credentialType: 'Advanced professional certification',
    description: 'Validate expertise in cloud architecture, data security, platform security, operations, and compliance.',
    category: 'security',
    difficulty: 'Advanced',
    duration: 'Experience requirement applies',
    costType: 'Paid',
    skills: ['Cloud security', 'Cloud architecture', 'Data security', 'Compliance'],
    officialUrl: 'https://www.isc2.org/certifications/ccsp',
    recommendedCareerPaths: ['cybersecurity', 'cloud-engineer'],
  },
  {
    id: 'isc2-csslp',
    name: 'Certified Secure Software Lifecycle Professional (CSSLP)',
    provider: 'ISC2',
    credentialType: 'Advanced professional certification',
    description: 'Validate secure software development expertise across requirements, design, implementation, testing, and deployment.',
    category: 'security',
    difficulty: 'Advanced',
    duration: 'Experience requirement applies',
    costType: 'Paid',
    skills: ['Secure development', 'Threat modeling', 'Software testing', 'Application security'],
    officialUrl: 'https://www.isc2.org/certifications/csslp',
    recommendedCareerPaths: ['cybersecurity', 'backend-dev', 'devops'],
  },
];

export const certificationVideos = [
  {
    id: 'video-ai-fundamentals',
    certificationId: 'microsoft-azure-ai-fundamentals',
    title: 'Azure AI Fundamentals Study Cram',
    channel: 'John Savill’s Technical Training',
    youtubeUrl: 'https://www.youtube.com/watch?v=E9aarWMLJw0',
    duration: '2h 5m',
    topic: 'Azure AI fundamentals concept review',
  },
  {
    id: 'video-sc-900',
    certificationId: 'microsoft-security-compliance-identity-fundamentals',
    title: 'SC-900 Security, Compliance, and Identity Study Cram',
    channel: 'John Savill’s Technical Training',
    youtubeUrl: 'https://www.youtube.com/watch?v=Bz-8jM3jg-8',
    duration: '2h 15m',
    topic: 'SC-900 exam domains',
  },
  {
    id: 'video-pl-900',
    certificationId: 'microsoft-power-platform-fundamentals',
    title: 'PL-900 Power Platform Fundamentals Study Cram',
    channel: 'John Savill’s Technical Training',
    youtubeUrl: 'https://www.youtube.com/watch?v=lbPHM-MiEUA',
    duration: '1h 53m',
    topic: 'PL-900 exam domains',
  },
  {
    id: 'video-aws-ai',
    certificationId: 'aws-certified-ai-practitioner',
    title: 'Cloud Computing Explained',
    channel: 'Simplilearn',
    youtubeUrl: 'https://www.youtube.com/watch?v=M988_fsOSWo',
    duration: '6m',
    topic: 'Cloud and AI foundations',
  },
  {
    id: 'video-google-cyber',
    certificationId: 'google-cybersecurity-professional',
    title: 'Cybersecurity for Beginners',
    channel: 'Google Career Certificates',
    youtubeUrl: 'https://www.youtube.com/watch?v=_DVVNOGYtmU',
    duration: '9m',
    topic: 'Cybersecurity foundations',
  },
  {
    id: 'video-google-data',
    certificationId: 'google-advanced-data-analytics',
    title: 'Data Analysis with Python',
    channel: 'freeCodeCamp.org',
    youtubeUrl: 'https://www.youtube.com/watch?v=GPVsHOlRBBI',
    duration: '4h 22m',
    topic: 'Python data analysis',
  },
  {
    id: 'video-ibm-cyber',
    certificationId: 'ibm-cybersecurity-analyst',
    title: 'A Beginner Cybersecurity Roadmap',
    channel: 'Cyber with Ben',
    youtubeUrl: 'https://www.youtube.com/watch?v=b12JrM-6DBY',
    duration: '15m',
    topic: 'Entry-level cybersecurity planning',
  },
  {
    id: 'video-ibm-devops',
    certificationId: 'ibm-devops-software-engineering',
    title: 'Docker Tutorial for Beginners',
    channel: 'TechWorld with Nana',
    youtubeUrl: 'https://www.youtube.com/watch?v=3c-iBn73dDE',
    duration: '2h 46m',
    topic: 'Containers and DevOps',
  },
  {
    id: 'video-github-foundations',
    certificationId: 'github-foundations',
    title: 'Git and GitHub for Beginners',
    channel: 'freeCodeCamp.org',
    youtubeUrl: 'https://www.youtube.com/watch?v=RGOj5yH7evk',
    duration: '1h 8m',
    topic: 'Git and GitHub foundations',
  },
  {
    id: 'video-linux-foundations',
    certificationId: 'linux-foundation-certified-it-associate',
    title: 'Introduction to Linux',
    channel: 'freeCodeCamp.org',
    youtubeUrl: 'https://www.youtube.com/watch?v=sWbUDq4S6Y8',
    duration: '6h 7m',
    topic: 'Linux foundations',
  },
  {
    id: 'video-comptia-cloud',
    certificationId: 'comptia-cloud-plus',
    title: 'Cloud Computing Explained',
    channel: 'Simplilearn',
    youtubeUrl: 'https://www.youtube.com/watch?v=M988_fsOSWo',
    duration: '6m',
    topic: 'Cloud computing foundations',
  },
  {
    id: 'video-comptia-data',
    certificationId: 'comptia-data-plus',
    title: 'Learn Data Science',
    channel: 'freeCodeCamp.org',
    youtubeUrl: 'https://www.youtube.com/watch?v=ua-CiDNNj30',
    duration: '5h 34m',
    topic: 'Data science foundations',
  },
  // Invalid or empty URLs are deliberately ignored by the UI.
  {
    id: 'video-validation-example',
    certificationId: 'comptia-data-plus',
    title: 'Unavailable sample',
    channel: 'Unknown',
    youtubeUrl: '',
    duration: '',
    topic: 'Validation example',
  },
];

export function loadCertificationCatalog() {
  return Promise.resolve(certifications);
}
